name: Meridian CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test --workspace
      - name: Clippy
        run: cargo clippy --workspace -- -A clippy::new_without_default -A clippy::empty_line_after_doc_comments -A clippy::doc_list_item_indentation -A clippy::collapsible_else_if -A clippy::manual_range_contains -A clippy::needless_range_loop -A clippy::map_or_default -A clippy::approx_constant

  build-no-std:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: thumbv7em-none-eabihf
      - uses: Swatinem/rust-cache@v2
      - name: Build HAL traits (no_std)
        run: cargo check --target thumbv7em-none-eabihf -p meridian-hal
      - name: Build types (no_std)
        run: cargo check --target thumbv7em-none-eabihf -p meridian-types
      - name: Build math (no_std)
        run: cargo check --target thumbv7em-none-eabihf -p meridian-math
      - name: Build sync (no_std)
        run: cargo check --target thumbv7em-none-eabihf -p meridian-sync
